# 异步传染

## 提出问题：

在ECMA Script 2016中提出的`async/await`，他规定了`await`必须在`async`函数中使用

```ts
async function getUser(){
	return await getUserRequest();
}
```

存在`async`关键字的函数被称为异步函数，而异步函数可以使用`await`来"等待"异步返回值

那如果同时存在多级等待：

```ts
async function request1(){
	return await request();
}
async function request2(){
	return await request1();
}
async function request3(){
	return await request2();
}
async function request4(){
	return await request3();
}
async function main(){
	const ans = await request4();
    console.log(ans);
}
```

想要等待一个`async`函数的返回值，就需要为修改当前函数为`async`函数，如此称为"传染"

<br>

有没有办法把异步写法改为同步写法？实现类似下面这样的调用

```ts
function getName() {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, 3000, "luowei");
  });
}

function main() {
  const name = getName();
  console.log(name);
  // luowei
}
```



## 解决过程：

这里我将引用卡颂大佬[React技术揭秘](https://react.iamkasong.com/)中的虚构语法做演示

我们虚构一个类似于`try...catch`语法——`try...handle`与两个操作符`perform`、`resume`

```ts
function getName() {
  const name = perform (() => new Promise((resolve, reject) => {
    setTimeout(resolve, 3000, "luowei");
  }))()
  return name;
}

function main() {
  const name = getName();
  console.log(name);
  // luowei
}

try{
	main();
} handle(value) {
    if(value instanceof Promise){
        value.then(name => {
            resume with name;
        })
    }else{
     	resume with value;
    }
}
```

当执行到`perform`操作符时会类似`throw`操作符一样，被最近的`try...handle`捕获，并且`perform`之后的参数将会作为`handle(name)`中的`name`值

他与`try...catch`唯一的区别在于`Error`在被`catch`捕获后之前的调用栈就销毁了，而`try...handle`会回到之前的调用栈

从这个例子可以看出，`try...handle` `perform` `resume`不区分同步与异步，这非常符合`代数效应`（代数效应在`React`中有很多应用）

分析一下这一段代码虚构的逻辑：

1. 调用`perform`，传入`perform`后的值
2. 被`handle`捕获，`resume`一个值作为`perform`操作返回值
3. 继续执行`perform`后续代码

上面也说过了，他与`try...catch`最大的区别在于`throw Error`被`try...catch`捕获后，源调用栈已经被销毁了，而在虚构语法中未被销毁，并且能够将`resume`值返回

<br/>

也就是说，我们可以尝试模拟一个`try...handle`过程，这里我们可以考虑`throw getName()`

将整个`getName()`返回的`promise`抛出

```ts
function run() {
    const cache = [];
    let index = 0;
    try {
        main();
    } catch (error) {
        if (error instanceof Promise) {
            error.finally(main);
        }
    }
}

run();
```

我们采用类似的语法`try...catch`，设计了一个`cache`和`index`来保存原调用栈异步函数返回结果

之前我们说过`try...catch`抛错后会销毁调用栈（`console.log(name)将不会被执行`），现在当`getName`返回结果时会再次调用`main`函数，重新执行`main`调用

由于`getName`已经返回值，我们希望新一轮`main`的调用时，`getName`的返回值能够从`cache`中同步获取，这里我们要对原方法进行一些更改

```ts
function run() {
    const cache = [];
    let index = 0;
    const _originGetName = getName;
    getName = () => {
        // 判断是否已经存在缓存值
        if (cache[index] && cache[index].status === "fulfilled") {
            return [cache[index].data, cache[index].err];
        }
        if (cache[index] && cache[index].status === "rejected") {
            return [cache[index].data, cache[index].err];
        }
        // 缓存值
        const promiseResult = {
            status: "pending",
            data: null,
            err: null,
        }
        cache[index++] = promiseResult;
        // 抛出源getName().then()，在其中修改promiseResult状态
        throw _originGetName("luowei").then(value => {
            promiseResult.status = "fulfilled";
            promiseResult.data = value;
        }, reason => {
            promiseResult.status = "rejected";
            promiseResult.data = reason;
        })
    }
    try {
        main();
    } catch (error) {
        if (error instanceof Promise) {
            const retry = () => {
                // 下标重置为0
                index=0;
                main();
            }
            error.finally(retry);
        }
    }
}

run();
```

我来梳理一下执行过程

![image-20230527135926778](/images/1.2.png)

通过这种调用，我们通过`throw Error`销毁原调用栈，在`catch`中等待异步返回值被缓存后，再重新执行`main`方法的思路，近似的模拟了`try...handle`语法中的功能，这就是异步转同步，解决异步传染的思路了



## 应用场景：

这种思路再`React Suspense`中有很有体现：

> 只要遵循一定规范，在FC中可以不区分同步、异步，以同样的方式从数据源中获取数据  
>
> ​																																					--《React设计原理》

```tsx
function AsyncComponent() {
  const [data, setData] = useState(null);
  useEffect(() => {
    fetchData().then(setData).catch(err => {
      throw err; 
    });
  }, []); 
  if(data) {
    return <Component data={data} /> 
  }   
  throw data;
}

<Suspense fallback={<Fallback />}>
  <AsyncComponent />
</Suspense>
```

![5.jpg](/images/1.4.awebp)

<br/>

参考文章：

[React 18 新特性（二）：Suspense & SuspenseList - 掘金 (juejin.cn)](https://juejin.cn/post/6994674140825272334#heading-4)



## 完整代码：

```ts
function getName() {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, 3000, "luowei");
  });
}

function main() {
  const name = getName();
  console.log(name);
  // luowei
}

function run() {
    const cache = [];
    let index = 0;
    const _originGetName = getName;
    getName = () => {
        // 判断是否已经存在缓存值
        if (cache[index] && cache[index].status === "fulfilled") {
            return [cache[index].data, cache[index].err];
        }
        if (cache[index] && cache[index].status === "rejected") {
            return [cache[index].data, cache[index].err];
        }
        // 缓存值
        const promiseResult = {
            status: "pending",
            data: null,
            err: null,
        }
        cache[index++] = promiseResult;
        // 抛出源getName().then()，在其中修改promiseResult状态
        throw _originGetName("luowei").then(value => {
            promiseResult.status = "fulfilled";
            promiseResult.data = value;
        }, reason => {
            promiseResult.status = "rejected";
            promiseResult.data = reason;
        })
    }
    try {
        main();
    } catch (error) {
        if (error instanceof Promise) {
            const retry = () => {
                // 下标重置为0
                index=0;
                main();
            }
            error.finally(retry);
        }
    }
}

run();
```

